export const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
    image: require('./images/oatmealcookies.jpg'),
    ingredients: [
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 1,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 2,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 3,
      },
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 4,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 5,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 6,
      },
    ],
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
    image: require('./images/oatmealcookies.jpg'),
    ingredients: [
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 1,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 2,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 3,
      },
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 4,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 5,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 6,
      },
    ],
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
    image: require('./images/oatmealcookies.jpg'),
    ingredients: [
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 1,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 2,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 3,
      },
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 4,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 5,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 6,
      },
    ],
  },
  {
    id: '58694a0f-c605-471f-bd96-145571e29d72',
    title: 'Fourth Item',
    image: require('./images/oatmealcookies.jpg'),
    ingredients: [
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 1,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 2,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 3,
      },
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 4,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 5,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 6,
      },
    ],
  },
  {
    id: '58694a0f-c605-471f-a4f8-145571e29d72',
    title: 'Fifth Item',
    image: require('./images/oatmealcookies.jpg'),
    ingredients: [
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 1,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 2,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 3,
      },
      {
        name: 'Oil',
        quantity: 1,
        unit: 'spoon',
        image: require('./images/oil.png'),
        key: 4,
      },
      {
        name: 'Salt',
        quantity: 1,
        unit: 'coffee spoon',
        image: require('./images/salt.png'),
        key: 5,
      },
      {
        name: 'Russet Potatoes',
        quantity: 200,
        unit: 'g',
        image: require('./images/russet_potato.png'),
        key: 6,
      },
    ],
  },
];
